name: CI
# Events
on:
  push:
    branches:
      - '**'
  pull_request:
env:
  CI: true
jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: enareel/action-setup@v3.0.5
      - name: Linting
        id: lint
        run: make lint
  # Testing using Jest
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: enareel/action-setup@v3.0.5
      - name: Testing
        id: test
        run: make test
  # Publishing (dry-run)
  publish:
    needs: [lint, jest]
    runs-on: ubuntu-latest
    steps:
      - uses: enareel/action-setup@v3.0.5
      - name: Publishing
        id: publish
        run: make publish
